# Generated by Django 5.2.4 on 2025-08-22 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_linked_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, may include +, space, -)', regex='^\\+?[0-9\\s\\-]{7,20}$')]),
        ),
    ]
