# Generated by Django 5.2.4 on 2025-11-02 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(error_messages={'unique': 'This mobile number is already in use.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, may include +, space, -)', regex='^\\+?[0-9\\s\\-]{7,20}$')]),
        ),
    ]
