# Generated by Django 5.2.4 on 2025-11-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0012_property_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRentalFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_scheduled', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_flags', to='properties.property')),
            ],
        ),
    ]
