# Generated by Django 5.2.4 on 2025-09-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('entities', '0003_alter_entity_created_at_alter_entity_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AddField(
            model_name='asset',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='Linked entity, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='entities.entity'),
        ),
    ]
