# Generated by Django 5.2.4 on 2025-09-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_phone'),
        ('properties', '0008_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='approach_road_width',
            field=models.PositiveIntegerField(blank=True, help_text='Road width (e.g., in feet)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='car_parks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height of floor (e.g., in feet)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='front_facing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('fully', 'Fully'), ('semi', 'Semi'), ('none', 'None')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gated_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_properties', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_properties', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(blank=True, choices=[('rental', 'Rental'), ('sale', 'Sale'), ('care', 'Care')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('under maintenance', 'Under Maintenance'), ('owner occupied', 'Owner Occupied'), ('tenant occupied', 'Tenant Occupied'), ('sold', 'Sold'), ('not_for_rent', 'Not for Rent')], default='vacant', max_length=20, null=True),
        ),
    ]
