# Generated by Django 5.2.4 on 2025-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_amenities_property_approach_road_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tenant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
