# Generated by Django 5.2.4 on 2025-09-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_phone'),
        ('properties', '0010_alter_property_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenant_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_properties', to='contacts.contact'),
        ),
    ]
