# Generated by Django 5.2.4 on 2025-09-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_phone'),
        ('properties', '0011_property_tenant_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to='contacts.contact'),
        ),
    ]
