# Generated by Django 5.2.4 on 2025-09-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_create_combined_ledger_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionledgercombined',
            options={'default_permissions': (), 'managed': False, 'ordering': ('-date', '-id')},
        ),
    ]
