# Generated by Django 5.2.4 on 2025-11-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_transactionledgercombined_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactionledgercombined',
            table='v_transaction_ledger_combined_v2',
        ),
    ]
