# Generated by Django 5.2.4 on 2025-08-28 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendor_address_alter_vendor_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gpay_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='GPay number must be a 10-digit number', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_method',
            field=models.CharField(choices=[('BANK', 'Bank'), ('UPI', 'UPI'), ('WALLET', 'Wallet')], default='BANK', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g. name@bank', max_length=100, null=True),
        ),
    ]
