# Generated by Django 5.2.4 on 2025-09-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_types', '0002_transactiontype_is_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='margin_applicable',
            field=models.BooleanField(default=False, help_text='Whether margin is applicable for this transaction type'),
        ),
    ]
