# Generated by Django 5.2.4 on 2026-03-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_types', '0003_transactiontype_margin_applicable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactiontype',
            unique_together=set(),
        ),
    ]
