# Generated by Django 5.2.4 on 2026-03-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_centres', '0001_initial'),
        ('transaction_types', '0004_alter_transactiontype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactiontype',
            unique_together={('cost_centre', 'name', 'direction')},
        ),
    ]
